project:
  type: website
  output-dir: docs

website:
  title: Andrey Davydov
  search: false
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: cv_davydov.qmd
        text: CV
      - href: current.qmd
        text: Research
      - href: teach.qmd
        text: Teaching
      - href: contact.qmd
        text: Contact
      
    collapse: true
format:
  html:
    theme: yoti.scss
    css: styles.css
    toc: true

editor: visual

