project:
  type: website
  output-dir: docs

website:
  title: "Andrey Davydov" 
  search: false
  navbar:
    right:
      - href: cv_davydov.qmd
        text: CV
      - href: research.qmd
        text: Research
      - href: teach.qmd
        text: Teaching
      - icon: envelope-at
        href: mailto:andreydavydov@mail.mcgill.ca

    collapse: true
format:
  html:
    theme: yoti.scss
    toc: true
    
editor: visual

