---
title: "Research"
page-layout: full
page-content: pandoc
---

**Projects**

<details open style="width: 100%; white-space: normal;">

<summary>“Ethnonationalism for Them, Multinationality for Us”: Domestic Adoption of International Radical Right Rhetoric by the Russian Regime</summary>


-   Looking at domestic propaganda, explores how the Russian regime selectively adopts radical right rhetoric for Western European and American contexts while maintaining a moderate stance on ethnic diversity for domestic contexts.

-   Uses frequency and sentiment analysis of over 20000 hour-long transcripts from major propaganda TV shows between 2017 and July 2024.

</details>

<details open style="width: 100%;">

<summary>Does the Discrepant Use of International Radical Right Rhetoric by the Russian Regime Provoke or Pacify the Opposition?</summary>


-   Compares official rhetoric to the rhetoric of diverse ideological strands of the opposition, ranging from social liberals to anti-immigrant far-right to pro-empire right.

-   Assesses whether the discrepancy in the regime's radical right rhetoric between foreign and domestic contexts makes the opposition more dissatisfied with the regime and with other opposition strands.

-   Uses frequency and sentiment analysis of transcripts of opposition programs on Youtube and posts on telegram channels.

</details>

**Peer-Reviewed Publications**

Davydov, A. (2017). Nativism versus right-wing transnationalism in American racial theories, 1914-1924. *Moscow University Bulletin. Series 19. Linguistics and Cross-Cultural Communication*, 2017(4), 146-153.

Davydov, A. (2016). Eastern European immigrants in American racial theories, 1914-1924. *Moscow University Bulletin. Series 19. Linguistics and Cross-Cultural Communication*, 2016(2), 125-132.

**Other Publications**

Davydov, A. (2021). Radical right ideologies and foreign policy preference: Attitudes towards Russia, China, and the USA in EU member states. Montreal, Canada: Resau transatlantique sur l'Europe politique (RESTEP).

Davydov, A. (2019) "Review of *The Lands in Between: Russia vs. the West and the New Politics of Hybrid War*, by Mitchell A. Orenstein." *Harvard Ukrainian Studies*, 36(3-4), 517-520.

<footer>

<p>© Andrey Davydov 2024</p>

</footer>
