---
title: "Teaching"
page-layout: full
---

**In Political Science**

<details open style="width: 100%;">

<summary>Lecturer at McGill University (2023-2024)</summary>

*Designed courses and taught them to undergraduate students.*

-   POLI 423 Politics of Ethno-Nationalism \[[Syllabus](POLI423_EthnoNationalism_syllabus.pdf){target="_blank"}\]
-   POLI 339 Nationalism, Ethnicity and the Radical Right in Europe \[[Syllabus](POLI339_NatRRightEurope_syllabus.pdf){target="_blank"}\]
-   POLI 431 Nations and States/Developed World \[[Syllabus](POLI431_NationsStates_syllabus.pdf){target="_blank"}\]

</details>

<details open style="width: 100%;">

<summary>Teaching Assistant at McGill University (2018-2023)</summary>

*Assisted faculty at the Department of Political Science by conducting conferences (seminars) and grading undergraduates.*

-   POLI 212 Government and Politics/Developed World
-   POLI 357 Politics: Contemporary Europe
-   POLI 339 Comparative Immigration Politics (Comparative/Developed)
-   POLI 442 International Relations of Ethnic Conflict
-   POLI 423 Politics of Ethno-Nationalism
-   POLI 329 Russian and Soviet Politics

</details>

------------------------------------------------------------------------

**Outside Political Science** (click to view)

<details open style="width: 100%;">

<summary>Lecturer at Lomonosov Moscow State University (2012-2017)</summary>

*Designed courses and taught them to undergraduate and graduate students. The courses on American and British culture were taught in English, the courses on Western European culture were taught in Russian.*

-   Race in 20th-Century American Culture
-   History of American Literature
-   History of American and British Literature (Early 20th Cent.)
-   History of Western European Literature (17th-18th Cent.)
-   History of Western European Literature (Early 19th Cent.)
-   History of Western European Literature (Late 19th Cent.)
-   History of Western European Literature (Early 20th Cent.)
-   Western European Cultural History (Late 19th Cent. and Early 20th Cent.)

</details>

<details open style="width: 100%;">

<summary>Lecturer at Knowledge Exchange Institute (2013-2017)</summary>

*Designed courses and taught them in English to American undergraduate exchange students at Lomonosov MSU.*

-   History of Russian Literature
-   Russian Cultural History

</details>

<footer>

<p>© Andrey Davydov 2024</p>

</footer>
